name: 'Build Docker Image'
description: 'Build, tag, and push image to Amazon '

inputs:
  Registry:
    description: 'Registry'
    required: true
  Repo:
    description: 'Repo'
    required: true
  branch:
    description: 'additional tag to identify latest build from branch'
    required: true
  branchTag:
    description: 'additional tag to identify latest build from branch Tag'
    default: ${{ github.sha }} 
  clusterName:
    description: 'ECS cluster'
    required: true
  resourceGroup:
    description: 'ECS service'
    required: true

outputs:
  image:
    description: 'ECR Registry'
    value: ${{ steps.build_image.outputs.image }}


runs:
  using: 'composite'
  steps:
    - name: Tag image
      id: build_image
      shell: bash
      run: |
        COMMIT_ID=$(echo ${{ inputs.branchTag }} | cut -c 1-7)
        IMAGE_TAG=$(echo ${{ inputs.branch }}-$COMMIT_ID)
        TAG=$(echo ${{ inputs.Registry }}/${{ inputs.Repo }})
        echo "image=$TAG:$IMAGE_TAG" >> $GITHUB_OUTPUT
    - name: Set up kubelogin for non-interactive login
      uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: 'v0.0.25'
    - name: Get K8s context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ inputs.resourceGroup }}
        cluster-name: ${{ inputs.clusterName }}
        admin: 'false'
        use-kubelogin: 'true'
